version: 2.4-{build}
configuration: Release

image: Visual Studio 2017

platform:
  - x64
  - Win32

branches:
   except:
      - tmp

install:
  - set POTRACE_VER=1.15
  - set FREETYPE_VER=2.9
  - set ZLIB_VER=1.2.11
  - set MIKTEX_SDK_VER=2.9.4106
  - set TTFA_VER=1.8.1
  - set TTFA_REV=2
  - cd vc
  - appveyor DownloadFile https://miktex.org/download/ctan/systems/win32/miktex/sdk/miktex-%MIKTEX_SDK_VER%-sdk.zip
  - unzip -o miktex-%MIKTEX_SDK_VER%-sdk.zip
  - del miktex-%MIKTEX_SDK_VER%-sdk.zip
  - cd freetype
  - appveyor DownloadFile http://download.savannah.gnu.org/releases/freetype/freetype-%FREETYPE_VER%.tar.gz
  - tar xzf freetype-%FREETYPE_VER%.tar.gz --strip-components=1
  - del freetype-%FREETYPE_VER%.tar.gz
  - patch -p1 <ft29-dll.patch
  - cd ..\potrace
  - appveyor DownloadFile http://potrace.sourceforge.net/download/%POTRACE_VER%/potrace-%POTRACE_VER%.tar.gz
  - tar xzf potrace-%POTRACE_VER%.tar.gz --strip-components=1
  - del potrace-%POTRACE_VER%.tar.gz
  - cd ..\zlib
  - appveyor DownloadFile http://zlib.net/zlib-%ZLIB_VER%.tar.gz
  - tar xzf zlib-%ZLIB_VER%.tar.gz --strip-components=1
  - del zlib-%ZLIB_VER%.tar.gz
  - cd ..
  - appveyor DownloadFile https://github.com/mgieseki/ttfautohint-dll/releases/download/r%TTFA_VER%-%TTFA_REV%/ttfautohint-%TTFA_VER%-dll64.zip
  - unzip -o -d ttfautohint ttfautohint-%TTFA_VER%-dll64.zip
  - del ttfautohint-%TTF_VER%-dll64.zip

build:
  project: vc\dvisvgm.sln
  verbosity: minimal
