language: cpp

compiler:
   - gcc
   - clang

before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -qq autotools-dev libkpathsea-dev libpotrace-dev libfreetype6-dev libgs-dev libz-dev texlive-base python-lxml libgtest-dev
   # Ubuntu doesn't provide pre-built gtest libraries, so we have to build them here.
   - "cd /usr/src/gtest/ && sudo cmake . && sudo cmake --build . && sudo mv libgtest* /usr/local/lib/ ; cd -"

script:
   - ./autogen.sh
   - ./configure
   - make
   - make check
