sudo: required
dist: trusty
group: legacy

language: cpp

compiler:
   - gcc
   - clang

branches:
   except:
      - tmp

before_install:
   - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
   - sudo apt-get update -qq
   - sudo apt-get install -qq autotools-dev libkpathsea-dev libpotrace-dev libfreetype6-dev libgs-dev libz-dev texlive-base python-lxml
   
install:
   - sudo apt-get install -qq g++-4.9
   - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 100

env:
   global:
      # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
      # via the "travis encrypt" command using the project repo's public key
      - secure: "MlOXG2PegI8ck67gSCoY0w4hncbaJ0UG+5VUOmzZ4blJDrA2BLOnQg8n/D65ic1pzmrooUuZJJMmgWI+6F+pyZyXTOpDP50cX4i8WpcuHY/phYp9w2jdN61YgqoUIgWgxsAxBUV2Lf1ULZbWYwUoI9fLkTE6owFXZPFT5ZQnwWA="

addons:
   coverity_scan:
      project:
         name: mgieseki/dvisvgm
         description: "dvisvgm - A fast DVI to SVG converter"
         version: 2.2
      notification_email: martin.gieseking@uos.de
      build_command_prepend: "./configure; make clean"
      build_command: "make -j"
      branch_pattern: coverity_scan

script:
   - uname -a
   - ./autogen.sh
   - ./configure
   - make
   - make -C src -t
   - make check
